ezrun_default_home:
    path: /
    defaults: { _controller: Default:index }

ezrun_default_test:
    path: /test
    defaults: { _controller: Default:test }
    requirements:
        _method: GET

ezrun_default_login:
    path: /login/{token}/{token2}
    defaults: { _controller: Default:login }